### ISSUE TITLE
Please release to a 0.5.1 galaxy

### ISSUE THREAD

**Issue by JocelynDelalande** [ginsys/ansible-role-nginx#1]
The released version on galaxy is totally broken.

Thanks by advance :)

**Comment by srgvg** [comment]
Hi @JocelynDelalande, sorry, only noticed this now :(

Can you be more specific on what is broken? I use that role myself regularly, and have zero problems :)

**Comment by srgvg** [comment]
I pushed some updates to sync with bennjoy's upstream and tagged that 0.5.1 but I still don't know which issues you have.

**Comment by srgvg** [comment]
Closing this as request is unclear. Feel free to comment

**Comment by JocelynDelalande** [comment]
Issues fixed with v0.5.1, thanks. I had an issue preventing any vhost to be used (something like `dict has no attribute "location"`), and sometimes, vhost no being picked up at all, sorry I didn't kept logs.
